baseurl = "http://willejs.io/"
languageCode = "en-us"
title = "Will Salt"
googleAnalytics = "UA-90822507-1"

[params]
  # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
  name = "Will Salt"
  description = "About Will Salt"

  [params.sidebar]
    avatar = "avatar.jpg"
    bio = "UNDER CONSTRUCTION"
    github = "willejs"
    linkedin = "https://www.linkedin.com/in/william-salt-7bb00819/"